### PR TITLE
migrate to typescript-eslint

### PR DESCRIPTION
**Pull request by timdeschryver**
- migrate to typescript-eslint
- updates the tooling
- modifies the build step
- publish the dist folder
- run build and test during CI
- adds util funtions

### CODE REVIEW

**Comment by Belco90** [comment]
I told you this several times before on DM but mate I can't thank you enough for this! The PR looks fantastic, I'll give it a try to the final bundle on my project during the weekend.

**Comment by Belco90** [comment]
I've published a beta version in npm, it's published [here](https://www.npmjs.com/package/eslint-plugin-testing-library/v/3.1.0-beta.2)

There are few things to fix:

-  now the folder to publish is `dist`rather than `.` so we need to config this in semantic release (I need to figure this)
- after installing it in another project, it doesn't seem to work properly:
image

I'm using node v10.20.1 and npm v6.14.4 but I can't find what's wrong here.

**Comment by timdeschryver** [comment]
1) Was it released via semantic release? It should've been configured with https://github.com/testing-library/eslint-plugin-testing-library/blob/08656c716909b053e3188c501b3ca181da8fc109/package.json#L23-L25

2) I'll take a look at it. I had the same problem while I did some tests with it, I must have forgotten to commit the change.

**Comment by timdeschryver** [comment]
Should be resolved with the latest commit, could you try again please?

**Comment by Belco90** [comment]
Published beta 3 and tested again. Looking fine now! We are ready to release it then, I’ll prepare everything for doing it tomorrow.

**Comment by Belco90** [comment]
@all-contributors please add @timdeschryver for infra and platform

**Pull request merged**
