### PR TITLE
feat(await-async-query,await-async-utils,await-fire-event): support handling promises with `jest-extended`'s `.toResolve` & `.toRejects`

### PR DESCRIPTION
**Pull request by NickBolles**
## Checks

- [x] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).
- [x] If some rule is added/updated/removed, I've regenerated the rules list (`npm run generate:rules-list`)
- [x] If some rule meta info is changed, I've regenerated the plugin shared configs (`npm run generate:configs`)

## Changes

Add support for marking usage of jest-extendeds `toResolve` and `toReject` ([docs](https://github.com/jest-community/jest-extended#promise)) as valid handling of promises.

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
This ESLint plugin is only about @testing-library testing frameworks.
If you want to have linting for `jest` & `jest-extended`, you should have a look at [`eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest) & [`eslint-plugin-jest-extended`](https://github.com/jest-community/eslint-plugin-jest-extended)

**Comment by Belco90** [comment]
@MichaelDeBoey  Can we rethink this? I would say this is a legit update for the rule. Such matchers can't be extended for the rule in `eslint-plugin-jest` or `eslint-plugin-jest-extended`. Since the matchers mentioned in this PR belong to jest, and the rule is tied to jest, I would say this is a valid case and should be merged.

**Comment by MichaelDeBoey** [comment]
Reading the rule README again, I think I misunderstood what @NickBolles was trying to do.

I indeed think this has a place in our plugin! 👍

**Comment by Belco90** [comment]
@MichaelDeBoey Great! I'll review this later.

**Review by Belco90 — CHANGES_REQUESTED** [review]
The change looks great! Since the change made to the `hasClosestExpectResolvesRejects` method affects to other rules, could you update their docs to mention those matchers are valid too? Those rules are:

- await-async-utils
- await-fire-event

**Comment by NickBolles** [comment]
@Belco90 updated! (with a copy/paste accident in the message for [d1cba9c](https://github.com/testing-library/eslint-plugin-testing-library/pull/612/commits/d1cba9cbfc2ab650667d3e1fa33b2c9e180927b1) :( )

**Comment by MichaelDeBoey** [comment]
@NickBolles Could you please also add tests for all these rules?

**Review by MichaelDeBoey — DISMISSED** [review]
@NickBolles Could you please also add tests for all these rules?

**Comment by Belco90** [comment]
> @NickBolles Could you please also add tests for all these rules?

Good catch, I missed this!

**Comment by Belco90** [comment]
@NickBolles Just a reminder you have some CI checks to fix!

**Comment by NickBolles** [comment]
@Belco90 sorry about such the delay on this. I've added tests for await-async-utils and await-fire-event, merged the latest from main and fixed the format issues.

**Review by Belco90 — APPROVED** [review]
LGTM!

**Comment by Belco90** [comment]
@all-contributors please add @NickBolles for code,test, and doc

**Pull request merged**
