### PR TITLE
chore: update dependencies + run prettier on codebase

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
BREAKING CHANGE: Requires Node@^10.22.1 || 12.x
BREAKING CHANGE: Requires ESLint@^7.5.x

### CODE REVIEW

**Comment by Belco90** [comment]
Tons of dev dependencies bumped. Are we sure we are not affected by any of their breaking changes? They'll be probably removing node v8 support and similar stuff, but still.

**Comment by MichaelDeBoey** [comment]
@Belco90 I checked them all out and only Node versions are really breaking in our case

**Review by Belco90 — APPROVED** [review]
Let's merge this one. Could you clarify why the minimum node version went from 10.12.0 to 10.22.1 please?

**Comment by Belco90** [comment]
@all-contributors please add @MichaelDeBoey for maintenance

**Comment by MichaelDeBoey** [comment]
@Belco90 It's because of the `@commitlint/cli` dependency

**Comment by Belco90** [comment]
That's just a dev dependency, it's not a breaking change then.

**Comment by MichaelDeBoey** [comment]
@Belco90 It is, but `>=10.22.1` is needed in order to being able to work on this package locally

**Comment by Belco90** [comment]
Sure, but won't be a breaking change for users using this package. So we need to remember to exclude that breaking change message to arrive to the final release.

**Pull request merged**
