### PR TITLE
refactor(node-utils): extract `isNodeOfType` functions

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Since all these functions are doing almost exactly the same, I extracted `isNodeOfType` and put all these kind of functions in a separate file.

@timdeschryver can probably help to make `isNodeOfType` more type-safe so we don't have to pass `NodeOfType` type anymore and we can do
```ts
export const isArrayExpression = isNodeOfType(AST_NODE_TYPES.ArrayExpression);
```
but I can't find it working atm.

### CODE REVIEW

**Review by timdeschryver — APPROVED** [review]
Hmmmm 🤔
I don't think that's possible because there's no "link" between `AST_NODE_TYPES` and `TSESTree.Node`.

**Comment by MichaelDeBoey** [comment]
@timdeschryver There actually is a 'link', as `TSESTree.Node` will have a type of the given `AST_NODE_TYPES` value.

I know it's a complex situation.
I know it is possible to do so, just can't figure out how to do so and was hoping you could help out here.
If not, I'll just leave it like this

**Comment by MichaelDeBoey** [comment]
@timdeschryver I updated `isNodeOfType` in 85ad91c and that seems to do what I want it to do.
Would love to have your feedback though.

**Comment by MichaelDeBoey** [comment]
Looking a bit further into it, the type predicates for union types are incorrect now. 😕🤔

`isLiteral` will check for 
```ts
| (BigIntLiteral & { type: 'Literal' })
| (BooleanLiteral & { type: 'Literal' })
| (NumberLiteral & { type: 'Literal' })
| (NullLiteral & { type: 'Literal' })
| (RegExpLiteral & { type: 'Literal' })
| (StringLiteral & { type: 'Literal' })
```
which is incorrect of course, as that should be
```ts
| (BigIntLiteral & { type: 'BigIntLiteral' })
| (BooleanLiteral & { type: 'BooleanLiteral' })
| (NumberLiteral & { type: 'NumberLiteral' })
| (NullLiteral & { type: 'NullLiteral' })
| (RegExpLiteral & { type: 'RegExpLiteral' })
| (StringLiteral & { type: 'StringLiteral' })
```

**Review by timdeschryver — COMMENTED** [review]
💯 Nice!

I learned something new. While it isn't 100% correct (as you mentioned), I think this covers our cases. Or we could create specific type utils for those cases if that's needed 🤔

**Comment by MichaelDeBoey** [comment]
Creating a new `isNodeOfUnionType` generic function (which will probably be the first implement I had) whenever we need it sounds good to me 👍

**Comment by MichaelDeBoey** [comment]
I just had a talk with @RobinMalfait and he suggested to have a look at https://www.typescriptlang.org/docs/handbook/2/mapped-types.html as this could possibly help us out here

Will check it out later today when I got some time

**Comment by Belco90** [comment]
@MichaelDeBoey thanks for your effort around this! It's something we definitely wanted to do on v4 but didn't have time to work on.

**Comment by MichaelDeBoey** [comment]
It seems like my second try is actually correct (even for union types)! 🎉

- [`BigIntLiteral`][BigIntLiteral],  [`BooleanLiteral`][BooleanLiteral], [`NumberLiteral`][NumberLiteral], [`NullLiteral`][NullLiteral], [`RegExpLiteral`][RegExpLiteral] & [`StringLiteral`][StringLiteral] all have `AST_NODE_TYPES.Literal` and are unioned as [`Literal `][Literal]
- [`MemberExpressionComputedName`][MemberExpressionComputedName] & [`MemberExpressionNonComputedName`][MemberExpressionNonComputedName] both have `AST_NODE_TYPES.MemberExpression` as `type` property and are unioned as [`MemberExpression`][MemberExpression]
- [`PropertyComputedName`][PropertyComputedName] & [`PropertyNonComputedName`][PropertyNonComputedName] both have `AST_NODE_TYPES.Property` as `type` property (see [`PropertyBase`][PropertyBase]) and are unioned as [`Property`][Property]

Thanks to @bmvantunes for pointing this out to me! 👊

[Literal]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L419-L425
[BigIntLiteral]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L827-L831
[BooleanLiteral]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L842-L845
[NumberLiteral]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L1156-L1159
[NullLiteral]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L1161-L1164
[RegExpLiteral]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L1197-L1200
[StringLiteral]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L1226-L1229

[MemberExpression]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L427-L429
[MemberExpressionComputedName]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L1123-L1126
[MemberExpressionNonComputedName]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L1128-L1131

[Property]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L473
[PropertyComputedName]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L1187-L1190
[PropertyNonComputedName]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L1192-L1195
[PropertyBase]: https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L699-L712

**Review by Belco90 — APPROVED** [review]
It looks so clean now 😮 

I'd like to wait for @timdeschryver's approval, who is the TS expert!

**Review by timdeschryver — APPROVED** [review]
This does (of course) have  my approval.
Good job @MichaelDeBoey 👏👏👏

**Pull request merged**
