### PR TITLE
Wrong link to docs in README

### PR DESCRIPTION
**Pull request by arvigeus**
Missing .md extension

### CODE REVIEW

**Comment by arvigeus** [comment]
Another one I found: [prefer-explicit-assert](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/docs/rules/prefer-explicit-assert.md) suggests using it in conjunction with prefer-expect-query-by, which seems not existing.

**Comment by Belco90** [comment]
> Another one I found: [prefer-explicit-assert](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/docs/rules/prefer-explicit-assert.md) suggests using it in conjunction with prefer-expect-query-by, which seems not existing.

Ah we forgot to remove that. Can you address that change too? Thanks!

**Comment by Belco90** [comment]
We can address the suggestion for non-existing rule in a different PR.

@all-contributors please add @arvigeus for docs

**Comment by arvigeus** [comment]
I'll remove the rule later today. Thanks!

**Comment by Belco90** [comment]
Don't worry! Addressed already in #78 

Thanks for catching this!

**Pull request merged**
