### PR TITLE
feat: support ESLint flat config

### LINKED ISSUE #853: Prepare the plugin for flat config
### Plugin version

n/a

### What problem do you want to solve?

- [Prepare the plugin for flat config](https://eslint.org/docs/latest/extend/plugin-migration-flat-config).

### Your take on the correct solution?

Apply the changes mentioned in the linked migration docs so the plugin is compatible with flat config mechanism

### Anything else?

_No response_

### Do you want to submit a pull request to implement this change?

Yes

### PR DESCRIPTION
**Pull request by Belco90**
## Checks

- [X] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).

## Changes

- Following [the official ESLint guide for making the plugin compatible with flat config](https://eslint.org/docs/latest/extend/plugin-migration-flat-config)

## Context

Closes #853

### CODE REVIEW

**Review by MichaelDeBoey — COMMENTED** [review]
I've seen multiple ESLint plugins that support both flat config & `.eslintrc` files, which could be a great upgrade path for people who can't use ESLint v9 (yet)

**Comment by Belco90** [comment]
@MichaelDeBoey Yes, planning to add compatibility with RC config finally, but will be a breaking change anyway (the configs will have a `-legacy` suffix as suggested in ESLint flat config migration guide).

**Comment by Belco90** [comment]
This should be a draft PR btw, but can edit that from the mobile app.

**Comment by smittysmee** [comment]
Where are we at with this guy? I am itching to use it!

**Comment by michaelfaith** [comment]
If you need any additional help with this, i'd be happy to pitch in.

**Pull request closed without merging**
