### PR TITLE
fix: `no-await-sync-events` false positive

### LINKED ISSUE #403: False positive for testing-library/no-await-sync-events
Using `await` with `userEvent.type`'s `delay` option is correct, but is incorrectly flagged as a lint error.

```js
async () => {
  const delay = 10
  // error  `userEvent.type` is sync and does not need `await` operator  testing-library/no-await-sync-events
  await userEvent.type(element, text, {delay})
}
  ```

### PR DESCRIPTION
**Pull request by sjarva**
## Checks

- [x] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).
- [ ] If some rule is added/updated/removed, I've regenerated the rules list (`npm run generate:rules-list`)
- [ ] If some rule meta info is changed, I've regenerated the plugin shared configs (`npm run generate:configs`)

## Changes

- Check if `delay` is declared or assigned a value elsewhere than in the call expression's arguments
- Add test cases that have declarations and assignments

## Context

Closes #403

### CODE REVIEW

**Comment by sjarva** [comment]
Oh wow, that must have been the fastest review in my life @Belco90 🥳 🎈 Thank you so much!

**Comment by Belco90** [comment]
It was a coincidence to be honest! I opened GitHub to check something else, and I saw this short PR 🚀

**Comment by ph-fritsche** [comment]
With `user-event@14` this rule should probably be removed as all APIs are asynchronous.

**Comment by Belco90** [comment]
> With `user-event@14` this rule should probably be removed, as all APIs are asynchronous.

It won't be removed yet, but we planned to adapt another rule to handle async user event method properly https://github.com/testing-library/eslint-plugin-testing-library/issues/626

**Pull request merged**
