### PR TITLE
feat: recommend no-wait-for-empty-callback

### PR DESCRIPTION
**Pull request by nickmccurdy**

### CODE REVIEW

**Comment by Belco90** [comment]
I'd say this shouldn't be a breaking change, or at least we haven't treat changes in presets as breaking changes. I should read more about this.

**Comment by nickmccurdy** [comment]
I thought they would be breaking changes since they could cause additional failures when the configs are in use. If you disagree I can rebase these to not include `BREAKING CHANGE:` and it will be a minor/patch release instead.

**Comment by Belco90** [comment]
Don't worry, I can address that when squashing and merging the PR. I'll read more about it and see how other libraries treat this.

**Comment by Belco90** [comment]
Ok so other plugins are handling this as a major release. I think it would be a good idea then to wrap all preset changes into a milestone, merge them into a v4 branch and wait for some other additions we have pending. So we release a v4 including several breaking changes for each preset update, and also add new rules and improvements. What do you think? I can create the branch and the milestone later.

**Comment by nickmccurdy** [comment]
That sounds good, what should I do with these pull requests for now though? Also, would it make sense to also have all the other changes related to #165 in this new release?

**Comment by timdeschryver** [comment]
a v4 is a good idea.
Looks like we will be adding more rules in a short time period.

@nickmccurdy when @Belco90 created a v4 branch,  we can rebase this PR to the v4 branch.

**Comment by Belco90** [comment]
Branch for `v4` created. You can update the PRs to point that branch now. I'm creating the milestone to track everything from #165 there.

**Pull request merged**
