### PR TITLE
chore: remove package lock

### PR DESCRIPTION
**Pull request by nickmccurdy**

### CODE REVIEW

**Comment by Belco90** [comment]
What is the motivation for this PR?

**Comment by gndelia** [comment]
I believe [here's the motivation](https://github.com/testing-library/pptr-testing-library/pull/47#issuecomment-689914532)

I'm not sure if I agree either but can't do more than that 🤷‍♂️

**Comment by Belco90** [comment]
I guess that's the reason, but not sure either if I agree.

**Comment by MichaelDeBoey** [comment]
`create-react-app` (and a lot of other big packages) also ignores lock files: https://github.com/facebook/create-react-app/pull/7789

**Pull request closed without merging**
