### PR TITLE
fix: handle multiple imports with `no-manual-cleanup`

### PR DESCRIPTION
**Pull request by maisano**
## Checks

- [x] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).

## Changes

Crawl all the import references when sniffing out `no-manual-cleanup` violations.

## Context

There is currently a bug with `no-manual-cleanup` where we only ever check the first import of any `testing-library` package. While duplicative imports of the _same_ package is very likely uncommon, there are many packages within the `testing-library` ecosystem that will trip up the package detection and break this rule when we only look at the first.

### CODE REVIEW

**Comment by maisano-patreon** [comment]
👋  Curious if I can get some eyes this, cc @Belco90

**Comment by Belco90** [comment]
I'll try to review this next week.

**Comment by maisano-patreon** [comment]
Hi hi – bumping this again! Should be a very quick review. The PR just accounts for when someone might have multiple testing library imports (which is common in my company's codebase).

**Review by Belco90 — APPROVED** [review]
LGTM, thanks for taking care of this!

**Comment by Belco90** [comment]
@all-contributors please add @maisano for code and test

**Pull request merged**
