### PR TITLE
fix(prefer-presence-queries): ignore `getBy*` inside `within` for on absence queries

### LINKED ISSUE #518: False positives with testing-library/prefer-presence-queries
### Plugin version

v5.0.0

### ESLint version

v8.2.0

### Node.js version

14.18.0

### npm/yarn version

1.22.17

### Operating system

Big Sur

### Bug description

Generally I like this rule but we have to disable it in quite a few places due to false positives with toBeNull.

### Steps to reproduce

Examples:

```typescript
expect(queryTooltip(screen.getByText('Some text'))).toBeNull();
```

```typescript
expect(within(screen.getByRole('dialog')).queryByText('Some text')).toBeNull();
```

```typescript
expect(screen.getByText('Some text').getAttribute('disabled')).toBeNull();
```

### Error output/screenshots

_No response_

### ESLint configuration

```js
    {
      files: ['src/**/*.test.[tj]s?(x)', 'src/test/**/*.[tj]s?(x)'],
      env: {
        jest: true,
        browser: true,
      },
      plugins: ['eslint-plugin-jest', 'eslint-plugin-testing-library'],
      extends: ['plugin:jest/recommended', 'plugin:testing-library/react'],
      rules: {
        // warning are under migration
        'testing-library/prefer-screen-queries': 'warn',
        'testing-library/no-render-in-setup': 'warn',
        'testing-library/render-result-naming-convention': 'warn',
        'testing-library/no-wait-for-multiple-assertions': 'warn',
        'testing-library/no-node-access': 'off'
      },
    },
```

### Rule(s) affected

testing-library/prefer-presence-queries

### Anything else?

_No response_

### Do you want to submit a pull request to fix this bug?

No

### PR DESCRIPTION
**Pull request by nathanmmiller**
…ence queries

## Checks

- [X] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).

## Changes

- Ignore getBy* nodes inside of within() for prefer-presence-queries when checking absence queries
- Added additional test case based on comments on https://github.com/testing-library/eslint-plugin-testing-library/pull/716

## Context

Fixes #518 [Well, partially fixes it.]

### CODE REVIEW

**Comment by Belco90** [comment]
@nathanmmiller Sorry, I'm not available yet. I hope I can check this by the end of the month.

**Comment by Belco90** [comment]
@nathanmmiller thanks for your patience! I'm slowly catching up, so I hope I can review it soon.

**Review by Belco90 — APPROVED** [review]
LGTM! Thanks for your contribution 💪

**Review by Belco90 — CHANGES_REQUESTED** [review]
Oh sorry, one change: can you add some examples with the `within` usage to the docs?

**Comment by Belco90** [comment]
Hey @nathanmmiller! It's been a while since you created this PR. Are you still willing to contribute?

**Comment by nathanmmiller** [comment]
Yes sorry for the delay. The remaining ask is just to add documentation,
right?

**Comment by Belco90** [comment]
@nathanmmiller yes, only doc changes and it's ready to go.

**Comment by nathanmmiller** [comment]
> @nathanmmiller yes, only doc changes and it's ready to go.

Docs added!

**Review by Belco90 — APPROVED** [review]
All good now! Thanks for your contribution 👌

**Comment by Belco90** [comment]
@all-contributors please add @nathanmmiller for code and test

**Pull request merged**
