### PR TITLE
test: adding test for possible false positive

### PR DESCRIPTION
**Pull request by gndelia**
adding a test to see if I can reproduce #241

### CODE REVIEW

**Comment by Belco90** [comment]
Can you remove the draft state from this one so we merge it?

**Comment by gndelia** [comment]
not sure if it makes sense to merge it. I opened in order to test the exact scenario (expression by expression 😋 ) mentioned in the bug, but I was unable to reproduce it. There's another test with the same scenario, but without checking the import; we would add that as we migrate the PRs in v4, so that would make this PR useless as the exact scenario will become covered (And more!)

If there's no response soon in the ticket, I guess we could just close it

**Comment by Belco90** [comment]
Ok, I see. Let's wait for v4 then.

**Comment by Belco90** [comment]
Ok, I see. Let's wait for v4 then.

**Comment by gndelia** [comment]
closing as the issue was closed

**Pull request closed without merging**
