### PR TITLE
fix: generate provenance statements on release

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
This will also add a new Provenance section + a verified badge next to the version (in the sidebar + versions tab) to the NPM page

More info can be found at https://docs.npmjs.com/generating-provenance-statements

### CODE REVIEW

**Review by Belco90 — APPROVED** [review]
TIL about provenance, thanks!

**Comment by Belco90** [comment]
@MichaelDeBoey I don't think this worked as expected? v6.3.2 was removed or hidden from npm registry somehow, [so the latest is still v6.3.1](https://www.npmjs.com/package/eslint-plugin-testing-library). Perhaps because its content is the same as the previous one?

**Comment by Belco90** [comment]
Interesting... it's back again in npm registry.

**Comment by MichaelDeBoey** [comment]
@antfu Maybe you have an idea what went wrong here? 🤔

**Pull request merged**
