### PR TITLE
fix: correct consistent-data-testid docs example

### PR DESCRIPTION
**Pull request by jmcriffey**
I just noticed the docs don't have the correct rule name here as I was having some trouble getting it to work.

### CODE REVIEW

**Comment by Belco90** [comment]
Thanks guys!

**Comment by Belco90** [comment]
This should be a doc PR type rather than fix to avoid releasing a new package tho. Not a big deal anyway.

**Comment by Belco90** [comment]
@all-contibutors please add @jmcriffey for doc

**Comment by Belco90** [comment]
@all-contributors please add @jmcriffey for doc

**Comment by Belco90** [comment]
@all-contributors please add @gndelia for review

**Comment by timdeschryver** [comment]
Ah got it @Belco90 , I'll try to remember it for next time + the contributors bot :)

**Comment by Belco90** [comment]
No problem. I guess I should add this to contributing guidelines or somewhere else?

**Comment by timdeschryver** [comment]
I don't have a strong opinion on this, but I guess it can't hurt to add it (or later if it happens too many times)

**Pull request merged**
